apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-nginx
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: sample-root-app
spec:
  project: default
  source:
    repoURL: https://github.com/PratyushMathur/gitops-repo.git
    targetRevision: HEAD
    path: app-of-apps/manifests/nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
